### ISSUE TITLE
Crash with redis-server 2.2.x

### ISSUE THREAD

**Issue by ricardograca** [MCProHosting/connect-smart-redis#2]
Using the redis-server as found in Ubuntu 12.04 results in the following error when attempting to save something to the session:

```
Error: ERR wrong number of arguments for 'set' command
at ReplyParser.<anonymous> (/var/www/devius.net/subdomains/balletrosa/htdocs/node_modules/redis/index.js:317:31)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_error (/var/www/devius.net/subdomains/balletrosa/htdocs/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/www/devius.net/subdomains/balletrosa/htdocs/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/www/devius.net/subdomains/balletrosa/htdocs/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/var/www/devius.net/subdomains/balletrosa/htdocs/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

When upgrading to redis-server 2.8.19 the error is no longer present and everything works as expected. I'm not sure if it's related to this [other bug](https://github.com/mranney/node_redis/issues/690) or if it's something else, but it could be useful to add a note about redis-server version compatibility in the readme.

**Comment by connor4312** [comment]
We make use of the SET command with the NX PX options specified. Redis server versions prior to 2.6.12 ([see note](http://redis.io/commands/set#options)) will not have it. That version of Redis was released about two years ago; we aren't really interested in continuing to support versions prior to it.

**Comment by ricardograca** [comment]
Sure I understand, but it would be useful for future users if the minimum redis version was in the README.

It only says it's inspired by connect-redis, which itself says minimum redis version is 2.0.0, so I assumed this module was the same, which made me waste some time trying to figure out what was wrong with my code.

**Comment by connor4312** [comment]
Ah sure thing, will do now
